dagster/src/utils/send_slack_master_release_notification.py
behaviour
Formats the Slack Master Release Notes
=> Format slack master release notes

dagster/src/data_quality_checks/geography.py, dagster/src/spark/transform_functions.py, dagster/src/spark/udf_dependencies.py
behaviour
Uses Mapbox Boundaries for country and in-country admin boundaries
=> Use Mapbox for all admin boundaries

dagster/src/spark/user_defined_functions.py
Replaces the GADM country check function with the Mapbox version
=> Replace GADM country function with Mapbox

dagster/Dockerfile, dagster/prod.Dockerfile
Moves assets to a new bucket. Old bucket is scheduled for deletion
=> feat: move assets to different bucket

dagster/src/spark/transform_functions.py
behaviour
Updates the file location of the disputed region file
=> Update the disputed region shapefile location

dagster/src/data_quality_checks/utils.py
Fix for issue in splitting of passed rows for returning only relevant columns
=> Update utils.py (#307)

infra/helm/dagster/values.yaml
- `build`: Commits that affect build components like build tool, dependencies, project
version
Increase concurrent runs from 1-2
=> build: increase concurrent runs

dagster/src/data_quality_checks/utils.py, docs/development.md, infra/helm/dagster/values.yaml
Fix the `[NUM_COLUMNS_MISMATCH]` bug when performing updates via giga sync
=> Fix num_columns_mismatch bug when making updates

dagster/src/assets/school_geolocation/assets.py
- `chore`: Miscellaneous commits (e.g. modifying `.gitignore`)
Add extra logging to `bronze_geolocation` step
=> chore: add extra logging

dagster/src/utils/delta.py
=> fix: swap constraint logic:

dagster/src/utils/delta.py
=> fix: always drop constraint in sync schema

dagster/src/utils/delta.py
prevents pipeline from failing when a constraint is created while it already exists
=> fix: accept duplicate constraint creation

dagster/src/assets/adhoc/qos_raw_csv_to_gold.py, dagster/src/constants/constants_class.py, dagster/src/jobs/adhoc.py, dagster/src/sensors/adhoc.py, docs/dataflow.md
=> feat: adds flow for adding qos_raw data

azure/templates/create-config.yaml, azure/templates/variables.yaml, dagster/src/assets/common/assets.py, dagster/src/internal/connectivity_queries.py, dagster/src/settings.py, dagster/src/spark/transform_functions.py, dagster/src/utils/db/gigamaps.py, dagster/src/utils/db/gigameter.py
behaviour
updates the sources of the realtime connectivity data and the logic
=> refactor: update connectivity data sources and logic

docs/development.md
- `docs`: Commits that affect documentation only
=> docs: update docs

dagster/src/spark/transform_functions.py
Correct the connectivity column logic
=> fix: correct the conectivity column logic

dagster/src/spark/transform_functions.py
Fix the connectivity column logic
=> fix: correct the conectivity column logic (#335)

dagster/src/assets/admin/assets.py
fix
Fix the incorrect constants import for admin__create_lakehouse_local asset
=> fix: incorrect import in admin__create_lakehouse_local

dagster/src/spark/udf_dependencies.py
- 
handle the result when the geopy result is empty
=> fix: handle the result when geopy result is empty

dagster/src/spark/transform_functions.py
The existing solution for GIGA-07 does not actually include the new columns from the `bronze` DF. This fix aims to account for that.
Rerun the staging run https://io-dagster-stg.unitst.org/runs/e461bf15-5a65-4ecb-8c10-e20fc09a14fe and assert that the dataframe shown after DF from create_bronze_layer_columns includes admin1_govt, admin2_govt, admin3_govt, and admin4_govt`
=> GIGA-07: Correct column selection logic in bronze layer transformation

dagster/src/utils/sentry.py
Since the `@capture_op_exceptions` decorator was attached to all assets, it was found to be incompatible with async assets such as `geolocation_data_quality_results_summary`. This fix aims to make `@capture_op_exceptions` work regardless of if the asset is sync or async.
Materialize an async asset such as `geolocation_data_quality_results_summary` and see if the below error still persists
```
dagster._core.errors.DagsterInvariantViolationError: Error with output for op "geolocation_data_quality_results_summary": output 'result' has generic output annotation, but did not receive an Output object for this output. Received instead an object of type <class 'coroutine'>
```
=> fix: make capture_op_exceptions compatible with async assets

dagster/src/assets/common/assets.py
Currently, in the `master` and `reference` assets, the null column handling logic is only applicable for `string` columns. This means that if a null column happens to be of another type, the output of these assets will also contain null values. This is especially important for non-nullable columns in the schema as this would trigger a `DELTA_NOT_NULL_CONSTRAINT_VIOLATED` error.
This fix aims to allow null handling for columns with types other than `string`.
Run a delete flow from Giga Sync
=> fix: null column handling in master and reference assets

dagster/src/assets/school_geolocation/assets.py, dagster/src/sensors/school_geolocation.py
It creates a table that stores the metadata from giga sync
=> feat: create giga sync metadata table

dagster/src/assets/school_geolocation/assets.py, dagster/src/sensors/school_geolocation.py
behaviour
Updates the name of the school geolocation metadata table and keeps it consistent
=> refactor: update school geolocation metadata table name

dagster/src/assets/adhoc/custom_dataset.py, dagster/src/assets/adhoc/master_csv_to_gold.py
- `chore`: Miscellaneous commits (e.g. modifying `.gitignore`)
Clears errors from failing pre-commit runs
=> chore: clear failures on pre-commit

dagster/src/assets/adhoc/master_csv_to_gold.py
behaviour
Add data via giga sync and this will add education_level_govt to the master
Add datasets via the backend and this will add education_level_govt to the master
=> refactor: move education_level_govt to master

dagster/src/spark/transform_functions.py
Reduce the likelihood that education level mapping is affected by how data is formatted. Especially the cases
=> fix: correct education level mapping

dagster/src/assets/adhoc/master_csv_to_gold.py
=> fix: update failing import

dagster/src/assets/adhoc/master_csv_to_gold.py
=> fix: correct db context import

dagster/src/data_quality_checks/create_update.py, dagster/src/spark/transform_functions.py
Refactored school ID validation to prevent school_id_giga overwrites during updates
Test an update with `school_id_giga` values different from those in silver/master. This should not result in duplicates being merged to the downstream tables due to different `school_id_giga` signatures.
=> fix: prevent school_id_giga from being overwritten in updates

dagster/src/assets/school_coverage/assets.py, dagster/src/assets/school_geolocation/assets.py, dagster/src/resources/__init__.py, dagster/src/resources/io_managers/intermediary_adls_delta.py
- `perf`: Commits are special `refactor` commits that improve performance
Removes the need for Pandas in the geolocation and coverage pipelines through replacing the Pandas-based IOManager with a Spark and Delta Table based IOManager
Test Giga Sync uploads for geolocation and coverage with high row-count files (e.g. > 10k)
GIGA-02
N/A
N/A
=> perf: optimize pandas in geolocation and coverage

dagster/src/assets/school_geolocation/assets.py, dagster/src/spark/transform_functions.py
Makes sure we always run the populate connectivity type logic to make the results predictable
=> fix: always populate connectivity type

dagster/src/assets/school_geolocation/assets.py, dagster/src/data_quality_checks/utils.py, dagster/src/sensors/school_geolocation.py, dagster/src/utils/data_quality_descriptions.py
behaviour
1. Keep only the relevant columns in the dq files instead of full list of dq columns
2. Also split the results into 2 separate DQ files
=> refactor: keep relevant columns in dq files

dagster/src/assets/school_geolocation/assets.py
=> fix: include uploaded columns parameter

dagster/src/assets/school_geolocation/assets.py, dagster/src/data_quality_checks/utils.py, dagster/src/resources/__init__.py, dagster/src/resources/io_managers/adls_generic_file.py, dagster/src/sensors/school_geolocation.py, dagster/src/utils/adls.py
Adds the legacy txt DQ report to outputs from giga sync
Upload files via giga sync and this should create a txt file under the `data-quality-results/dq-report` folder in the blob storage container
=> feat: create summary txt DQ report

dagster/Dockerfile, dagster/prod.Dockerfile, dagster/src/resources/superset.py
- `chore`: Miscellaneous commits (e.g. modifying `.gitignore`)
Move spark installer to giga owned storage bucket
1. Go to azure devops
2. deploy dev against this branch
3. monitor if dagster unexpectedly failes runs that would have typically passed
=> chore: move giga assets to giga owned storage

dagster/src/data_quality_checks/utils.py, dagster/src/spark/transform_functions.py
Adds functionality to add admin 3 and admin 4 to school data within the pipeline, where available
=> feat: add admin 3 and 4 levels

dagster/src/assets/school_geolocation/assets.py, dagster/src/spark/config_expectations.py
Ensures that all columns that need to have title case values are title case always
=> fix: ensure title case for binary columns

dagster/src/internal/common_assets/master_release_notes.py, dagster/src/utils/send_slack_master_release_notification.py
Adds updated columns to master release notes
=> feat: add updated columns to slack master release notes

dagster/src/utils/datahub/emit_dataset_metadata.py, dagster/src/utils/datahub/validator.py
Only emit `school_master` or `qos` assets
https://app.clickup.com/t/25789471/TECH-6059
=> fix: silence datahub emits in prod

dagster/src/assets/adhoc/health_master_csv_to_gold.py, dagster/src/assets/school_geolocation/assets.py, dagster/src/data_quality_checks/standard.py, dagster/src/data_quality_checks/utils.py, dagster/src/sensors/adhoc.py, dagster/src/spark/config_expectations.py, dagster/src/spark/transform_functions.py, dagster/src/utils/nocodb/get_nocodb_data.py
Uses human-readable name mapping from nocodb
=> feat: use nocodb for dq columns human readable
